### ISSUE TITLE
NPE in Snapshot when doing conn.queryWithParams

### ISSUE THREAD

**Issue by aliakhtar** [vert-x3/vertx-jdbc-service#8] opened 2015-02-13 07:58 UTC
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:396)
	at io.vertx.ext.jdbc.impl.actions.AbstractJdbcStatement.asList(AbstractJdbcStatement.java:85)
	at io.vertx.ext.jdbc.impl.actions.JdbcQuery.executeStatement(JdbcQuery.java:41)
	at io.vertx.ext.jdbc.impl.actions.JdbcQuery.executeStatement(JdbcQuery.java:32)
	at io.vertx.ext.jdbc.impl.actions.AbstractJdbcStatement.execute(AbstractJdbcStatement.java:52)
	at io.vertx.ext.jdbc.impl.actions.AbstractJdbcAction.handle(AbstractJdbcAction.java:48)
	at io.vertx.ext.jdbc.impl.actions.AbstractJdbcAction.handle(AbstractJdbcAction.java:33)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:217)
	at io.vertx.core.impl.ContextImpl$$Lambda$32/20130473.run(Unknown Source)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$191(OrderedExecutorFactory.java:91)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$12/142749.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by purplefox** [comment] 2015-02-13 16:47
I've added a possible fix (in master). As I can't reproduce this (do you have a reproducer?) it's a bit of a guess.

Please tell me if it fixes the issue.

**Comment by aliakhtar** [comment] 2015-02-14 10:30
Thanks for the fix. I can't test it as I had to revert to M2 to keep my code working. When the next milestone is out, hopefully with fixes to the JsonObject / Array issue, I can give it another try.

**Comment by purplefox** [comment] 2015-03-23 14:50
Closing this. If problem persists please reopen.

**Closed** 2015-03-23 14:50 UTC
